# HumeBots/                                      _ 
# | |  | |                                      | |
# | |__| |_   _ _ __ ___   ___  ___ ___  _ __ __| |
# |  __  | | | | '_ ` _ \ / _ \/ __/ _ \| '__/ _` |
# | |  | | |_| | | | | | |  __/ (_| (_) | | | (_| |
# |_|  |_|\__,_|_| |_| |_|\___|\___\___/|_|  \__,_|

# Placeholder for use in about_response in lang.yml.
# Should show off all the other bots you have, if any.
other_bots: |
  â†’ **HumeBot**
  â€¢ The ultimate Discord bot, featuring every feature in every other
  â€‹ â€‹ â€‹ â€‹bot I have.
  â€¢ [Learn more](https://humeman/bots/humebot) | [Invite](https://discord.com/api/oauth2/authorize?client_id=768606643780190218&permissions=8&scope=bot)

  â†’ **teck tip bot**
  â€¢ An advanced copypasta bot, featuring cross-server, fully customizable, 
  â€‹ â€‹ â€‹ â€‹user-curated content. Also includes the HumeTunes music system.
  â€¢ [Learn more](https://humeman/bots/tecktip) | [Invite](https://discord.com/oauth2/authorize?client_id=679005043361447973&permissions=104188992&scope=bot)

# Bots to check for in !overrides.
# Only applies to API enabled bot.
override_bots: 
  - humebot
  - tecktip

# Bot groups
# All groups inherit everything below them.
# For example, dev has the permissions of every group listed,
#   and VIPs also have all default perms.
groups:
  default:
    name: Default
    description: All users.
    emoji: ğŸ¥‰

  vip:
    name: VIP
    description: Cool people.
    emoji: ğŸ¥ˆ

  awesome:
    name: Awesome
    description: Cooler people.
    emoji: ğŸ¥‡

  mod:
    name: Moderator
    description: Coolerer people.
    emoji: ğŸª™

  dev:
    name: Developer
    description: Coolest people.
    emoji: ğŸ› ï¸